name: Build creation

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"    
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository

      - name: Use Node.js 20.18.0
        uses: actions/setup-node@v1
        with:
          node-version: 20.18.0

      - name: Install packages
        run: npm i
     
      - name: Create Prod build
        run: npm run build  
