name: Build Size Comment

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [master]

jobs:
  comment-build-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Project
        run: npm run build
      
      - name: Calculate Build Size
        run: |
          prod_size=$(du -sh build/ | awk '{print $1}')
          echo "PROD_SIZE=$prod_size" >> $GITHUB_ENV

      - name: Find and Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { repo, owner } = context.repo;
            const prs = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open',
              base: 'master'
            });

            if (prs.data.length > 0) {
              const prNumber = prs.data[0].number;
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: prNumber,
                body: `## 📦 Production Build Size

                Total Size: ${process.env.PROD_SIZE}

                *Automated build size tracking*`
              });
            }